name: CardLib CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@master
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: compile lib
      run: mkdir build && cmake -Bbuild/
    
    - name: build lib
      run: cmake --build build/ --config Debug --target cardlib
