name: CardLib CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: compile lib
      run: mkdir build && cmake -Bbuild/
    
    - name: build lib
      run: cmake --build build/ --config Debug --target cardlib
